name: 'CasaGiralda '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14636
title: Hostería Casa Giralda
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#71d331'
    - '#a53131'
    - '#998f52'
    - '#000000'
  brandStrength: 0.3125
  lightness: 0.2669301563873887
  saturation: 0.7080324681010097
  rhythmicContrast: 0.7294143864419311
purpose: []
